version: '3.3'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    ports:
      - 8000:80
    links:
      - fpm
    volumes:
      - ./:/var/www/test-task-1
  fpm:
    build:
      context: .
      dockerfile: docker/fpm.dockerfile
    volumes:
      - ./:/var/www/test-task-1
    links:
      - db
  db:
    image: postgres:13.1
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=test-task-1
